helm/Chart.lock
helm/values-prod.yaml

fix deploy

---

src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/ReceiptToReviewed.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/ReceiptToReviewedTest.java

- Refactored API ReceiptToReviewed following [analysis](https://pagopa.atlassian.net/wiki/spaces/PPR/pages/822870269/Analisi+APIs+Monitoring+Recover+helpdesk-receipt)
- Updated unit tests
[Issue PRDP-252](https://pagopa.atlassian.net/browse/PRDP-252?atlOrigin=eyJpIjoiYmJiN2RlY2I4NmU1NGE1OGEwYmU1M2U2Y2RjN2VlYjEiLCJwIjoiaiJ9)

[PRDP-253] Refactor ReceiptToReviewed API

---

src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceiptError.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/ReceiptCosmosClientImpl.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceiptErrorTest.java

- Introducing /errors-toreview/<bizvent-id> endpoint management through new http triggered function
- Updated unit tests
Introducing new endpoints to inspect existing data as part of manual recovery process on failures

[PRDP-256] feat: get Errors to review endpoint

---

README.md
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceipt.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceiptByOrganizationFiscalCodeAndIUV.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/BizEventCosmosClient.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/BizEventCosmosClientImpl.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceiptByOrganizationFiscalCodeAndIUVTest.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceiptTest.java

- added new API to retrieve the receipt from CosmosDB
- added unit test
- updated README.md
Implemented APIs defined in https://pagopa.atlassian.net/wiki/spaces/PPR/pages/822870269/Analisi+APIs+Monitoring+Recover+helpdesk-receipt#API-getReceipt-%3Awip%3A

[PRDP-251] feat: Add get receipt API

---

src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/entity/event/InfoTransaction.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/entity/event/Transaction.java

- Added new biz event fields
Alline with ReceiptGenerator changes ([PR-98](https://github.com/pagopa/pagopa-receipt-pdf-generator/pull/98))

[feat] Added new fields to transaction details

---

openapi/openapi.json
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceipt.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceiptByOrganizationFiscalCodeAndIUV.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceiptError.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceiptPdf.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedReceipt.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedReceiptMassive.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceipt.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceiptMassive.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RegenerateReceiptPdf.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceiptByOrganizationFiscalCodeAndIUVTest.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceiptErrorTest.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceiptTest.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedReceiptMassiveTest.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedReceiptTest.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceiptMassiveTest.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceiptTest.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RegenerateReceiptPdfTest.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/ReceiptQueueClientImplTest.java

- Allined API error responses to follow the scheme in the [analysis](https://pagopa.atlassian.net/wiki/spaces/PPR/pages/822870269/Analisi+APIs+Monitoring+Recover+helpdesk-receipt)
- Updated openApi specs
[Issue PRDP-269](https://pagopa.atlassian.net/browse/PRDP-269?atlOrigin=eyJpIjoiYmY4N2VkNjk1MDhlNDQ3ZTk5YjliZDg1ZGU2MWQyMDUiLCJwIjoiaiJ9)

[PRDP-269] Updated openapi specs and API error responses

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

chore: Add flag

---

src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BizEventToReceiptServiceImpl.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedReceiptTest.java

- Introduced recovery from transaction details of payer data

[PRDP-281] feat: add recovery of payer fiscal code from details

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

fix env var

---

src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/BizEventCosmosClientImpl.java

- Added bizEvent status filter in query
Need to filter bizEvent not in status DONE

[feat] Added bizEvent status filter in query

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

chore: Upd config processi helpdesk schedulati

---

helm/values-prod.yaml

chore: Upd prod helm

---

src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/RecoverNotNotifiedReceiptUtils.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceiptMassiveTest.java

feat: Add limit on io error to notify massive recover

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/RecoverNotNotifiedReceiptUtils.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceiptMassiveTest.java

feat: Add env to customize limit on io error to notify massive recover

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
integration-test/src/features/receipt_pdf_helpdesk.feature
integration-test/src/script/teardown_script.js
integration-test/src/step_definitions/common.js
integration-test/src/step_definitions/receipt_pdf_helpdesk_step.js
integration-test/src/step_definitions/receipts_datastore_client.js
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceiptMessage.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/ReceiptCosmosClient.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/ReceiptCosmosClientImpl.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/entity/receipt/IOMessage.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/exception/IoMessageNotFoundException.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/ReceiptCosmosService.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/ReceiptCosmosServiceImpl.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceiptMessageTest.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/ReceiptCosmosClientImplTest.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/ReceiptCosmosServiceImplTest.java

- Introducing getReceiptMessage API
https://pagopa.atlassian.net/jira/software/c/projects/PRDP/boards/440?selectedIssue=PRDP-302

[PRDP-302] feat: add recover message to helpdesk

---

integration-test/src/step_definitions/api_helpdesk_client.js

- Fix missing function for getReceiptMessage int. test

[PRDP-302] feat: fix api_helpdesk_client.js

---

openapi/openapi.json

[PRDP-302] chore: updated openapi.json

---

README.md
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi.json
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/GetCart.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/ReceiptCosmosClient.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/ReceiptCosmosClientImpl.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/entity/cart/CartForReceipt.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/entity/cart/CartStatusType.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/exception/CartNotFoundException.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/ReceiptCosmosService.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/ReceiptCosmosServiceImpl.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/GetCartTest.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/ReceiptCosmosClientImplTest.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/ReceiptCosmosServiceImplTest.java

- added getCart api
- added unit test
- updated openapi.json

[PRDP-307] feat: API getCart

---

src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/entity/receipt/Receipt.java

- Added isCart field to Receipt
[Issue PRDP-286](https://pagopa.atlassian.net/browse/PRDP-286?atlOrigin=eyJpIjoiZGM2YjAyYmU2ZjIzNDQzMGE4NWNlNGYwYTJhZGY1YjgiLCJwIjoiaiJ9)

[PRDP-286] Added isCart field to Receipt

---

src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BizEventToReceiptServiceImpl.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/BizEventToReceiptUtils.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/ReceiptToReviewedTest.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceiptTest.java

- Introducing format fixes for grandTotal in helpdesk APIs

fix: grand total amount format

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
integration-test/src/config/.env.dev
integration-test/src/config/.env.local
integration-test/src/config/.env.uat
integration-test/src/features/receipt_pdf_helpdesk.feature
integration-test/src/step_definitions/api_helpdesk_client.js
integration-test/src/step_definitions/biz_events_datastore_client.js
integration-test/src/step_definitions/common.js
integration-test/src/step_definitions/receipt_pdf_helpdesk_step.js
integration-test/src/step_definitions/receipts_datastore_client.js
openapi/openapi.json
pom.xml
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedCart.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedCartMassive.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedCartScheduled.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/CartReceiptsCosmosClient.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/ReceiptCosmosClient.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/CartReceiptsCosmosClientImpl.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/ReceiptCosmosClientImpl.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/entity/cart/CartForReceipt.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/entity/receipt/Receipt.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/ReceiptCosmosServiceImpl.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/BizEventToReceiptUtils.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/ReceiptCosmosClientImplTest.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/ReceiptCosmosServiceImplTest.java

- Added integration test for recoverFailedCart API
- Added integration test for recoverFailedCartMassive API
- Fixed `recoverFailedCart` endpoint path
- Added field `inserted_at` in cart
- Fixed amount formatting 
- Fixed cart cosmos client container env name
- Fixed cart output binding collection name
- Removed JsonProperty Annotation from receipt fields

[PRDP-291] feat: Add integration test for cart API

---

src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BizEventToReceiptServiceImpl.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/BizEventToReceiptUtils.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedCartTest.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedReceiptMassiveTest.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedReceiptScheduledTest.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedReceiptTest.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BuildTemplateServiceImplTest.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/BizEventToReceiptUtilsTest.java

-Updated Helpdesk APIS with new cf validation checks

feat: add cf checks to helpdesk

---

src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BizEventToReceiptServiceImpl.java

- Inverted payer tax code checks

[PRDP-337] fix: Inverted payer tax code checks

---

src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/BizEventToReceiptUtils.java

- Added check on transaction origin when checking payer fiscal code
A receipt document was inserted even if the payer wasnt from an auth channel origin

[fix] Added check on transaction origin when checking payer fiscal code

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

chore: Fix cfg helm env

---

src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RegenerateReceiptPdf.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/BizEventCosmosClientImpl.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/entity/event/enumeration/BizEventStatusType.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BizEventToReceiptServiceImpl.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/GenerateReceiptPdfServiceImpl.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/BizEventToReceiptUtils.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RegenerateReceiptPdfTest.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/GenerateReceiptPdfServiceImplTest.java

- Fixed some issues when regenerating the PDF receipt
- handled the new INGESTED state and fixed some incorrect behavior
- manual and junit test

bug: [PagoPa-1838] fix issues in regenerate pdf receipt

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi.json
pom.xml
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BuildTemplateServiceImpl.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BuildTemplateServiceImplTest.java

- deleted exception and replaced with blank
- error during PDF generation in case of missing payer's name and surname
- manual and junit test

feat: [PAGOPA-1882] receipt PDF Generation even in the absence of the payer's name and surname

---

host.json
pom.xml
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/ReceiptToReviewed.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedCart.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedCartMassive.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedCartScheduled.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedReceipt.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedReceiptMassive.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedReceiptScheduled.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceipt.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceiptMassive.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceiptScheduled.java
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RegenerateReceiptPdf.java

https://learn.microsoft.com/en-us/azure/azure-functions/migrate-cosmos-db-version-3-version-4?tabs=isolated-process&pivots=programming-language-java
Azure Functions upgrade and maintenance
- Tested in local and DEV environment

[PAGOPA-2017] chore: Upgrade ExtensionBundle

---

.github/workflows/integration_test.yml
helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi.json
pom.xml
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/ReceiptBlobClientImpl.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/ReceiptBlobClientImplTest.java

- fixed receipt file name construction logic in regenerate API
[PIDM-167](https://pagopa.atlassian.net/browse/PIDM-167)
[PIDM-167]: https://pagopa.atlassian.net/browse/PIDM-167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PIDM-167] fix: Regenerate pdf file name

---

.github/workflows/code_review.yml
.github/workflows/deploy_with_github_runner.yml
.github/workflows/integration_test.yml
.github/workflows/release-deploy.yml
.identity/.terraform.lock.hcl
.identity/00_data.tf
.identity/03_github_environment.tf
.identity/99_main.tf
helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

- Implemented new runner
- Implemented workload identity with helm version 7.5.0
[PIDM-482](https://pagopa.atlassian.net/browse/PIDM-482)
[PIDM-482]: https://pagopa.atlassian.net/browse/PIDM-482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: [PIDM-482] Implement workload identity & new runner

---

helm/values-prod.yaml

chore: Disable crons helpdesk

---

helm/template/configmaps.yaml
src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BuildTemplateServiceImpl.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BuildTemplateServiceImplTest.java
src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/util/ObjectMapperUtils.java
src/test/resources/biz-events/bizEventGuest.json
src/test/resources/psp_config_file.json

- added new local payments method name map
- updated build receipt PDF template logic to use new payments method name map
- fixed  build receipt PDF template logic by adding missing:
- config map for brand logo and relative logic
- wisp logic
- updated unit tests
[PIDM-352](https://pagopa.atlassian.net/browse/PIDM-352)
[PIDM-352]: https://pagopa.atlassian.net/browse/PIDM-352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PIDM-352] fix: Payment method name mapping

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

- Added missing payment method config map to helm
[PAGOPA-731](https://pagopa.atlassian.net/browse/PIDM-731)
[PAGOPA-731]: https://pagopa.atlassian.net/browse/PAGOPA-731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [PIDM-731] Added payment method config map to helm

---

helm/template/configmaps.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

- Added payment method Klarna
[PIDM-733](https://pagopa.atlassian.net/browse/PIDM-733)
[PIDM-733]: https://pagopa.atlassian.net/browse/PIDM-733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [PIDM-733] Add payment method Klarna
